name: ci
on:
  workflow_call:
    inputs:
      split-subtrees:
        description: Whether or not to split subtrees
        required: false
        type: boolean
        default: false
      run-psalm:
        description: Whether or not to run Psalm static analysis
        required: false
        type: boolean
        default: false
    secrets:
      ci-ssh-key:
        description: The SSH key for splitting subtrees
        required: false
jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - php: '8.2'
            stability: prefer-stable
          - php: '8.3'
            stability: prefer-stable
    name: PHP ${{ matrix.php }} - ${{ matrix.stability }}
    steps:
      - name: Check Out Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set Up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: curl, dom, libxml, mbstring, pcntl, xdebug, zip
          tools: composer:v2
          coverage: xdebug
      - name: Install Dependencies
        run: composer update --${{ matrix.stability }} --prefer-dist --no-interaction --no-progress
      - name: Run Tests
        run: composer phpunit
      - name: Run Linter
        run: PHP_CS_FIXER_IGNORE_ENV=1 composer phpcs-test
      - name: Run Psalm Static Analysis
        if: inputs.run-psalm == true
        run: composer psalm -- --shepherd
      - name: Upload Coverage Results To Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          composer global require php-coveralls/php-coveralls
          php-coveralls --coverage_clover=./.coverage/clover.xml --json_path=./coveralls-upload.json -v
      - name: Split Subtrees
        if: inputs.split-subtrees == true && matrix.php == '8.2' && (github.ref == 'refs/heads/1.x' || startswith(github.ref, 'refs/tags/'))
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.ci-ssh-key }}"
          bash bin/split.sh ${{ github.ref }}
