name: ci
on:
  push:
    branches:
      - '*.x'
  pull_request:
  schedule:
    - cron: '0 0 * * *'
jobs:
  ci:
    uses: ./.github/workflows/ci-template.yml
    with:
      split-subtrees: true
      run-psalm: true
    secrets:
      ci-ssh-key: ${{ secrets.CI_SSH_KEY }}
