name: ci
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'
jobs:
  ci:
    uses: aphiria/aphiria/.github/workflows/ci-template.yml@1.x
      with:
        # Set this to true once we've closed https://github.com/aphiria/aphiria/issues/154
        run-psalm-static-analysis: false
        split-subtrees: true
