name: ci
on:
  push:
    branches:
      - '*.x'
    tags:
      - '*'
  pull_request:
  schedule:
    - cron: '0 0 * * *'
jobs:
  ci:
    uses: ./.github/workflows/ci-template.yml
    with:
      split-subtrees: true
      run-php-cs-fixer: false
      run-psalm: false
    secrets:
      ci-ssh-key: ${{ secrets.CI_SSH_KEY }}
      temp-github-pat: ${{ secrets.TEMP_GITHUB_PAT }}
