name: ci
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'
jobs:
  ci:
    uses: aphiria/aphiria/.github/workflows/ci-template.yml@1.x
    with:
      split-subtrees: true
      run-psalm: true
    secrets:
      ci-ssh-key: ${{ secrets.CI_SSH_KEY }}
